# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180313_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creatred',
            new_name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
